### ISSUE TITLE
Wrong loss function in paper/poster?

### ISSUE THREAD

**Issue by LiranPo** [sjmoran/DeepLPF#11]
Hi,
I believe the paper and poster both show a loss function with contradictive parts: the first part (`Lab`) gets bigger as images are more _different_, whereas the second part (`MS-SSIM`) gets bigger as images are more _similar_.
![image](https://user-images.githubusercontent.com/37546907/118670197-10b87680-b7ff-11eb-97cb-3c3f4aaa6667.png)
The code, however, does not make that mistake, and actually the loss is `Lab + (1 - MS-SSIM)` (not sure why `1` is necessary).

**Comment by sjmoran** [comment]
Hi @LiranPo, thank you for highlighting this typo - you are correct the loss should be Lab + (1-MS-SSIM) in the paper and in the poster.

**Comment by LiranPo** [comment]
@sjmoran another note about the poster (screenshot above) - I believe you mean `Lab` and `MS-SSIM` account for global and local enhancement, respectively, not vice versa, as stated in your paper:
![image](https://user-images.githubusercontent.com/37546907/118791986-e7035c00-b89f-11eb-9348-4951ca8e39af.png)
