### ISSUE TITLE
Varying input image size

### ISSUE THREAD

**Issue by LiranPo** [sjmoran/DeepLPF#12]
Hello,
Could you please explain how DeepLPF handles various image sizes at (1) train time (2) inference/prediction time?
Also if you could point to parts of the code that support that, that would be highly appreciated.
Thanks!

**Comment by sjmoran** [comment]
Hi Liran, please see the up/down sampling performed here: 

https://github.com/sjmoran/DeepLPF/blob/322e9e0fdc2f64814e2090e328d5aa1b7378a627/model.py#L320
https://github.com/sjmoran/DeepLPF/blob/322e9e0fdc2f64814e2090e328d5aa1b7378a627/model.py#L506
https://github.com/sjmoran/DeepLPF/blob/322e9e0fdc2f64814e2090e328d5aa1b7378a627/model.py#L707

The up/down sampling of the spatial dimensions to 300x300 pixels ensures the data going into the network has the right shape both at training and at inference time.
