### ISSUE TITLE
Input to filter blocks

### ISSUE THREAD

**Issue by LiranPo** [sjmoran/DeepLPF#13]
Hi,
According to your poster, the elliptical and graduated filters should be taking `concat(y_hat_2, backbone_features)` as input, yet according to the following code (see starting point), all 3 filter block types (incl. polynomial/cubic) take `concat(y_hat_1, backbone_features)`
https://github.com/sjmoran/DeepLPF/blob/322e9e0fdc2f64814e2090e328d5aa1b7378a627/model.py#L997
![image](https://user-images.githubusercontent.com/37546907/119838649-413d9600-bf0c-11eb-9dbe-9c0e46ec85dc.png)

Could you please help clarify?

Thanks!

**Comment by sjmoran** [comment]
Hi @LiranPo, thank you for your continued interest in DeepLPF! The results in the paper were collated with the connectivity as shown in the above diagram.  However, both ways work well, so feel free to choose which is best for your task.
