### ISSUE TITLE
RuntimeError: Given groups=1, weight of size [16, 3, 3, 3], expected input[1, 4, 345, 514] to have 3 channels, but got 4 channels instead

### ISSUE THREAD

**Issue by suitmyself** [sjmoran/DeepLPF#16]
RuntimeError: Given groups=1, weight of size [16, 3, 3, 3], expected input[1, 4, 345, 514] to have 3 channels, but got 4 channels instead

**Comment by sjmoran** [comment]
Check your input image. It appears to have 4 channels rather than 3. The 4th is possibly an alpha channel. If that is the case just select the first 3 channels which should be the RGB channels.

**Comment by suitmyself** [comment]
I just run the inference with the image provided by this repo.
It seems that `pillow.Image.open` read image with 'RGBA' 4 channels, not 'RGB' 3 channels.
So I add 'convert('RGB')' as follows:
`img = ImageProcessing.normalise_image(np.array(Image.open(img_filepath).convert('RGB')), normaliser) `
