### ISSUE TITLE
data.py only have 248 lines

### ISSUE THREAD

**Issue by wangchx67** [sjmoran/DeepLPF#17]
I want to train the DeepLPF again, but I see the data.py only have 248 lines, so where should I modify the path?

In the other hand, I want to know what means of 3 pre-trained models, I think the adobe_dpe is 2250 training images and 500 testing images, adobe_upe is 4500 training images and 500 testing image, but how about distort-and-recover?

Last question, how do you export the MIT-ADOBE-FIVEK datasets, do you have do any operation such as resizeing? 

I use fivek datasets last 500 images as testing images which resize to have a long-edge of 512 pixels in your three pre-trained model and  get a not very good result (psnr 21.57 in dpe, 22.51 in upe and 20.87 in distort-and-recover)

**Comment by wangchx67** [comment]
> 
Sorry, I find distort-and-recover is 4750 training images  and 250 testing images. am I right?

**Comment by wangchx67** [comment]
> I want to train the DeepLPF again, but I see the data.py only have 248 lines, so where should I modify the path?
> 
> In the other hand, I want to know what means of 3 pre-trained models, I think the adobe_dpe is 2250 training images and 500 testing images, adobe_upe is 4500 training images and 500 testing image, but how about distort-and-recover?
> 
> Last question, how do you export the MIT-ADOBE-FIVEK datasets, do you have do any operation such as resizeing?
> 
> I use fivek datasets last 500 images as testing images which resize to have a long-edge of 512 pixels in your three pre-trained model and get a not very good result (psnr 21.57 in dpe, 22.51 in upe and 20.87 in distort-and-recover)

I have trained successfully.

**Comment by sjmoran** [comment]
Great, glad you have it working. Any further questions please reach out.
