### ISSUE TITLE
hello, I am very interested in your work. Could you upload your supplementary material or your codes

### ISSUE THREAD

**Issue by Fanbenchao** [sjmoran/DeepLPF#2]

**Comment by sjmoran** [comment]
Hi, thank you for your interest. The supplementary is here: http://www.seanjmoran.com/pdfs/DeepLPF_supplementary.pdf. The code is in the process of being made public and will appear here: https://github.com/huawei-noah.

**Comment by Fanbenchao** [comment]
Thank you for reply!

**Comment by sjmoran** [comment]
Code and supplementary now available
