### ISSUE TITLE
Poor performance on MIT Adobe Fivek datasets

### ISSUE THREAD

**Issue by Fanbenchao** [sjmoran/DeepLPF#4]
Hello, thank you for excellent work! I have met some problem when I trained and tested your model on the dataset mentioned in your paper.  I follow the ways mentioned in DPE to process the MIT Adobe FiveK dataset and use their test list for testing. However, I got very poor performance with PSNR 17.49 dB on the FiveK-DPE test dataset.
the following is my processed image paired.
![0001](https://user-images.githubusercontent.com/30153284/91284043-fac0dc80-e7bd-11ea-8bd5-06c4c159aca7.jpg)
input image
![0001](https://user-images.githubusercontent.com/30153284/91284086-08766200-e7be-11ea-82c2-e3b613708a45.jpg)
expertC image

**Comment by sjmoran** [comment]
Hi, thank you for your interest in our work. I would hazard a guess that your network isn't learning anything given the very low PSNR. I would suggest checking your data pre-processing (e.g. ensure data is appropriately normalised, ensure you have got the Adobe5k dataset pre-processing steps correct as detailed on the README in our repository - this can be a bit tricky). For example, your expertC image above doesn't appear to match the expertC image at the Adobe5K website: https://data.csail.mit.edu/graphics/fivek/.

**Comment by Fanbenchao** [comment]
Thank you for your suggestions. Yes, you're right! Our expertC images don't match the expertC image at the Adobe5k. I'll try process the expertC following your repository.

**Comment by deepisp** [comment]
Yes, it can be a little tricky to get the pre-processing right in Lightroom, but those Github threads linked to in our README will allow you to exactly replicate the dataset pre-processing for our paper and the other papers (e.g. DPE). The Adobe5k website can be used to cross-check your pre-processed images with how they should look, and that way you will be able to tell if you have it right.

**Comment by sjmoran** [comment]
Yes, it can be a little tricky to get the pre-processing right in Lightroom, but those Github threads linked to in our README will allow you to exactly replicate the dataset pre-processing for our paper and the other papers (e.g. DPE). The Adobe5k website can be used to cross-check your pre-processed images with how they should look, and that way you will be able to tell if you have it right.

**Comment by nile649** [comment]
@Fanbenchao out of curiosity why not directly use the Adobe 5k expertc data instead of pre-processing by yourself.

**Comment by sjmoran** [comment]
While being close, Adobe5k expertC (from the Adobe5k website) does not quite match the specifications used by the DPE etc authors e.g. the DPE authors have long edge 512 pixels etc.

**Comment by nile649** [comment]
Thanks
