### ISSUE TITLE
about the traning dataset

### ISSUE THREAD

**Issue by monsterlyg** [sjmoran/DeepLPF#6]
The original mit-adobe-fivek dpe if too big for me and as you said"Lightroom to pre-process the images according to the procedure outlined in the DeepPhotoEnhancer (DPE) paper". Can you provide with a processed input dataset?

**Comment by sjmoran** [comment]
No, unfortunately. You will need to pre-process the dataset on your end by downloading the original images from the Adobe5K (https://data.csail.mit.edu/graphics/fivek/) website and using the instructions in the README in the DeepLPF repository to pre-process with Lightroom.
