### ISSUE TITLE
Issue in data.py

### ISSUE THREAD

**Issue by ash80** [sjmoran/DeepLPF#7]
Line 232 in data.py should be `img_id = file.split(".")[0]`  instead of `img_id = file.split("-")[0]`

**Comment by sjmoran** [comment]
Thank you, it depends on the input data file naming convention - do change this to the format that works for your data.

**Comment by ash80** [comment]
Hi @sjmoran, 
The `.` was supposed to separate the filename from its extension.
Commonly, a filename and extension are separated with a `.` rather than `-`. Wouldn't it make sense if it's the same in this code?
