### ISSUE TITLE
Test on custom dataset

### ISSUE THREAD

**Issue by ShenZheng2000** [sjmoran/DeepLPF#9]
Hello, Authors! Thanks for your excellent work. I would like to know whether it is possible to test custom images other than the Adobe dataset. In the code, I found that the data loader is just for Adobe.

**Comment by sjmoran** [comment]
Hi, thank you for your interest in our work! Yes, you can easily try any other image dataset by creating your own data loader. The adobe data loader is an example of how a data loader should work (in that case for the adobe image dataset).
